version: '3'
services:

  openresty:
    image: zobuodomain/96875:1
    volumes:
      - "/home/node/app"

    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - redis


  redis:
    image: redis:7.0
